//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardLocker.recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardLocker.recursos.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquear teclado.
        /// </summary>
        internal static string ActionLock {
            get {
                return ResourceManager.GetString("ActionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear teclado.
        /// </summary>
        internal static string ActionUnlock {
            get {
                return ResourceManager.GetString("ActionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyboard Locker.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teclado quedó desactivado. Usa el icono de la bandeja para reactivarlo..
        /// </summary>
        internal static string BalloonLockedMessage {
            get {
                return ResourceManager.GetString("BalloonLockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teclado bloqueado.
        /// </summary>
        internal static string BalloonLockedTitle {
            get {
                return ResourceManager.GetString("BalloonLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teclado volvió a estar disponible..
        /// </summary>
        internal static string BalloonUnlockedMessage {
            get {
                return ResourceManager.GetString("BalloonUnlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teclado desbloqueado.
        /// </summary>
        internal static string BalloonUnlockedTitle {
            get {
                return ResourceManager.GetString("BalloonUnlockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo instalar el hook global del teclado..
        /// </summary>
        internal static string ErrorInstallHook {
            get {
                return ResourceManager.GetString("ErrorInstallHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener el módulo principal..
        /// </summary>
        internal static string ErrorMainModule {
            get {
                return ResourceManager.GetString("ErrorMainModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        internal static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: teclado bloqueado.
        /// </summary>
        internal static string StatusLocked {
            get {
                return ResourceManager.GetString("StatusLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: teclado desbloqueado.
        /// </summary>
        internal static string StatusUnlocked {
            get {
                return ResourceManager.GetString("StatusUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bloqueado.
        /// </summary>
        internal static string TrayLocked {
            get {
                return ResourceManager.GetString("TrayLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a desbloqueado.
        /// </summary>
        internal static string TrayUnlocked {
            get {
                return ResourceManager.GetString("TrayUnlocked", resourceCulture);
            }
        }
    }
}
